### ISSUE TITLE
Docker setup

### ISSUE THREAD

**Issue by ioiste** [nymanjens/facto#1]
Hello!
 
I'm looking into some tools I could use for family transactions tracking and Facto seems promising. However I'm interested in running/hosting this via Docker. I briefly tried to get it up and running, but didn't have much success building the image and I don't really know any Scala so the errors were not that helpful to me.
 
Would you be kind to help us, Docker users, by publishing a docker image for Facto on [Docker Hub](https://hub.docker.com/) or maybe commit a [`Dockerfile`](https://docs.docker.com/engine/reference/builder/) containing the build instructions for the application's image?

Thank you for making this open-source software and keep up the great work!

**Comment by nymanjens** [comment]
Hi,

I'm happy that you are considering my project :-).

> but didn't have much success building the image

Not sure if this is what you did, but if you follow the guide in the README (https://github.com/nymanjens/facto#installation), you don't need to build anything, just run the precompiled binary.

> Would you be kind to help us, Docker users, by publishing a docker image for Facto on Docker Hub or maybe commit a Dockerfile containing the build instructions for the application's image?

I'd be happy to provide Docker support, but I unfortunately don't have any experience with Docker (and I don't have the bandwidth to get to know it for the moment). I would be happy to review a pull request or add a file if you send it, if that can help.

**Comment by ioiste** [comment]
I completely understand the lack of bandwidth! 😄 
Just like you, I'm doing this in my spare time as a hobby, so I might not always answer fast. If someone else has experience with Dockerizing Scala apps, they're welcome to step in and help us.

After downloading and unpacking the binaries (compiled files) with demo configuration I've tried following the guide in the Readme inside an OpenJDK Docker image, with the following (Dockerfile) instructions:

(Ran with `docker build /path/to/facto_binaries_and_Dockerfile --network network_with_mysql_running`)
```
FROM openjdk:8-jre

COPY ./ /app

WORKDIR /app

# Create database tables
RUN bin/server -DdropAndCreateNewDb && rm RUNNING_PID

# Create admin user
RUN bin/server -DcreateAdminUser && rm RUNNING_PID

# Run application
RUN bin/server

EXPOSE 9000
```

I have edited `application.conf` with the MySQL 5.7 server connection details, changed the app secret and default password. When it gets to Step 4/7 : `RUN bin/server -DdropAndCreateNewDb && rm RUNNING_PID`, it successfully connects to the database but after that I get a lot of `IllegalArgumentException` errors, like so:

```
[info] application - Creating Pool for datasource 'default'
[info] p.a.d.DefaultDBApi - Database [default] connected at jdbc:mysql://mysql_db/facto?user=someuser&password=somepassword
[error] application - Error when parsing accounting-config.yml: java.lang.IllegalArgumentException: requirement failed: description cannot contain placeholders (Transaction = Transaction(Common,,ENDOW,Endowment for ${account.longName},0.0,,null))
	at scala.Predef$.require(Predef.scala:277)
	at app.models.accounting.config.Parsable$Template$Transaction.parse(Parsable.scala:191)
	at app.models.accounting.config.Parsable$Template.$anonfun$parse$15(Parsable.scala:161)
	at scala.collection.immutable.List.map(List.scala:283)
	at app.models.accounting.config.Parsable$Template.parse(Parsable.scala:161)
	at app.models.accounting.config.Parsable$Config.$anonfun$parse$7(Parsable.scala:42)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at app.models.accounting.config.Parsable$Config.parse(Parsable.scala:41)
	at app.models.accounting.config.ConfigModule.config(ConfigModule.scala:45)
	at app.models.accounting.config.ConfigModule$$FastClassByGuice$$d15760b8.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:402)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:409)
	at play.api.inject.ContextClassLoaderInjector.$anonfun$instanceOf$3(Injector.scala:118)
	at play.api.inject.ContextClassLoaderInjector.withContext(Injector.scala:126)
	at play.api.inject.ContextClassLoaderInjector.instanceOf(Injector.scala:118)
	at play.api.inject.RoutesProvider.$anonfun$get$2(BuiltinModule.scala:107)
	at scala.Option.fold(Option.scala:158)
	at play.api.inject.RoutesProvider.get$lzycompute(BuiltinModule.scala:107)
	at play.api.inject.RoutesProvider.get(BuiltinModule.scala:103)
	at play.api.inject.RoutesProvider.get(BuiltinModule.scala:102)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

I'm pretty sure it has something to do with the way I'm trying to build the image / use the binaries inside the image. Shouldn't the OpenJDK - jre 8 work fine as an environment to run the application? Or maybe there's something else Facto needs in order to run? 
Any other ideas? 🤔

**Comment by nymanjens** [comment]
Hmm, this sounds like a bug in facto itself. I'll take a look this week.

**Comment by ioiste** [comment]
Oh, ok, let me know so I can try again after a possible fix.
Should it help, here's the full (excessively large) errors log: https://pastebin.ubuntu.com/p/xTHqxTZZzQ/. Pastebin seems to have some issues (502 Bad Gateway).

Thank you!

**Comment by nymanjens** [comment]
I fixed the error you mentioned in https://github.com/nymanjens/facto/commit/84a6d822a25600263a04f88add6f8044a0e296dc

**Comment by nymanjens** [comment]
I spent some time trying to get Docker to work (my first time). I did the following:

- Changed `application.conf` with following line: `db.default.url="jdbc:mysql://localhost:3306/facto?user=root&password=change_this_default_password"`
- Ran the following docker commands in the unpacked release folder (with updated conf):

```
docker network create facto_network

docker run --name=facto_mysql --net=facto_network \
  --env="MYSQL_ROOT_PASSWORD=change_this_default_password" \
  --env="MYSQL_DATABASE=facto" \
  -d mysql/mysql-server:latest

docker build . --network facto_network
```

But facto can't seem to find MYSQL:

```
Sending build context to Docker daemon  72.83MB
Step 1/7 : FROM openjdk:8-jre
 ---> d9d1d3243082
Step 2/7 : COPY ./ /app
 ---> 01feffbd32d4
Step 3/7 : WORKDIR /app
 ---> Running in 9a55818bf9b9
Removing intermediate container 9a55818bf9b9
 ---> 73f57f00523e
Step 4/7 : RUN bin/server -DdropAndCreateNewDb && rm RUNNING_PID
 ---> Running in 2b79b3d72aaf
[info] application - Creating Pool for datasource 'default'
[error] c.z.h.p.HikariPool - HikariPool-1 - Exception during pool initialization.
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:400)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1038)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:339)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2247)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2280)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2079)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:214)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:298)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2247)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2280)
Oops, cannot start the server.
Configuration error: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.configError(Configuration.scala:156)
	at play.api.Configuration.reportError(Configuration.scala:990)
	at play.api.db.DefaultDBApi.$anonfun$connect$1(DefaultDBApi.scala:48)
	at play.api.db.DefaultDBApi.$anonfun$connect$1$adapted(DefaultDBApi.scala:42)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at play.api.db.DefaultDBApi.connect(DefaultDBApi.scala:42)
	at play.api.db.DBApiProvider.get$lzycompute(DBModule.scala:86)
	at play.api.db.DBApiProvider.get(DBModule.scala:75)
	at play.api.db.DBApiProvider.get(DBModule.scala:56)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:62)
	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:987)
	at com.google.inject.util.Providers$GuicifiedProviderWithDependencies.initialize(Providers.java:149)
	at com.google.inject.util.Providers$GuicifiedProviderWithDependencies$$FastClassByGuice$$2a7177aa.invoke(<generated>)
	at com.google.inject.internal.SingleMethodInjector$1.invoke(SingleMethodInjector.java:54)
	at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:89)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80)
	at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:223)
	at com.google.inject.internal.Initializer.injectAll(Initializer.java:132)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:174)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

Since you got this to work, what commands did you use?

**Comment by nymanjens** [comment]
### Update:

I got a little bit further:

- Changed `application.conf` with following line: `db.default.url="jdbc:mysql://facto_mysql:3306/facto?user=root&password=facto"`
- Ran the following docker commands in the unpacked release folder (with updated conf):

```
docker network create facto_network

docker run --name=facto_mysql --net=facto_network \
  --env="MYSQL_ROOT_PASSWORD=facto" \
  --env="MYSQL_DATABASE=facto" \
  -d mysql/mysql-server:latest

docker build . --network facto_network
```

But facto can't seem to find MYSQL:

```
java.sql.SQLException: null,  message from server: "Host '192.168.11.3' is not allowed to connect to this MySQL server"
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
```

**Comment by ioiste** [comment]
After your fix, it works past that build step now, nice!
For me, it seemed to have an issue with generating the tables' structure:

```
[info] application - Creating Pool for datasource 'default'
[info] p.a.d.DefaultDBApi - Database [default] connected at jdbc:mysql://mysql_db/facto?user=user&password=pwd

  Dropping the database tables (if present) and creating new ones...
[warn] c.z.h.HikariConfig - The initializationFailFast propery is deprecated, see initializationFailTimeout
Oops, cannot start the server.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Invalid default value for 'transactionDate'
  at app.tools.ApplicationStartHook.<init>(ApplicationStartHook.scala:23)
  at Module.configure(Module.scala:11) (via modules: com.google.inject.util.Modules$OverrideModule -> Module)
  while locating app.tools.ApplicationStartHook

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Invalid default value for 'transactionDate'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:400)
        at com.mysql.jdbc.Util.getInstance(Util.java:383)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3847)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3783)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1901)
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1193)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$5.$anonfun$run$5(JdbcActionComponent.scala:290)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$5.$anonfun$run$5$adapted(JdbcActionComponent.scala:290)
        at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:372)
        at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:367)
        at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:434)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$5.$anonfun$run$4(JdbcActionComponent.scala:290)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$5.$anonfun$run$4$adapted(JdbcActionComponent.scala:290)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$5.run(JdbcActionComponent.scala:290)
        at slick.jdbc.JdbcActionComponent$SchemaActionExtensionMethodsImpl$$anon$5.run(JdbcActionComponent.scala:288)
        at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:31)
        at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

But I got past the issue by building my MySQL server with the [--explicit_defaults_for_timestamp flag](https://github.com/jhipster/generator-jhipster/issues/5743#issuecomment-301334695). I'm using MySQL 5.7.31-1debian10 (MySQL 8 does not seem to work with Facto, probably due to some compatibility issues) and my guess is that you're using some other MySQL version which does not need this flag. It'd be nice to either have the exact version of your MySQL server in order to avoid this workaround or have this fixed some other way.

At this moment, I can get the application up and running from (Docker's point of view) with this Dockerfile:

```
FROM openjdk:8-jre

COPY ./ /app

WORKDIR /app

# Create database tables
RUN bin/server -DdropAndCreateNewDb && rm RUNNING_PID

# Create admin user
RUN bin/server -DcreateAdminUser && rm RUNNING_PID

EXPOSE 9000

CMD ["bin/server"]
```

And the whole network + mysql flow like this:

```
docker network create facto_network

docker run --name=facto_mysql --network=facto_network \
  --env="MYSQL_ROOT_PASSWORD=change_this_default_password" \
  --env="MYSQL_DATABASE=facto" \
   -p 3360:3360 \
   -d mysql:5.7 \
    --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp

docker build --tag facto:3.25 . --network facto_network

docker run  --network facto_network --publish 9000:9000 --detach --name facto facto:3.25
```

And facto is running at localhost:9000. 
Ideally, I'd be using Facto as a container in a docker-compose configuration and since the stuff above works, it sholdn't pose any issues after, in a perfect setting, the app has an image on Docker Hub.

Now I've got the app running with Docker, but after I login in I get an error like this in the browser's developer console: `java.lang.IllegalArgumentException: requirement failed: No user exists with loginName 'alice'`. 
Any ideas on this one?
Here are the full logs: https://pastebin.com/qLvd2wHF

I like that we're making progress! 😄

**Comment by nymanjens** [comment]
Oh wow, it's great that you got this running!

> It'd be nice to either have the exact version of your MySQL server in order to avoid this workaround or have this fixed some other way.

Looks like I'm using MariaDB (but with the Java JDBC profile for MySQL):
```
$ mysqld --version
mysqld  Ver 10.3.22-MariaDB-0+deb10u1 for debian-linux-gnueabihf on armv8l (Raspbian 10)
```

> java.lang.IllegalArgumentException: requirement failed: No user exists with loginName 'alice'.

The issue is that the config file assumes there is a user named 'alice' (and also one named 'bob') that are tied to accounts. This leads to a catch-22 because you can't add users without logging in and you can't login because of this error.

I updated the config file in the release zip:
https://pastebin.com/raw/vNiDXyCL

On my computer, it's working now with Docker (after updating `play.http.secret.key`)

**Comment by ioiste** [comment]
> Looks like I'm using MariaDB (but with the Java JDBC profile for MySQL):
> 
> ```
> $ mysqld --version
> mysqld  Ver 10.3.22-MariaDB-0+deb10u1 for debian-linux-gnueabihf on armv8l (Raspbian 10)
> ```
Alright, I'll try my next setup using MariaDB.

> The issue is that the config file assumes there is a user named 'alice' (and also one named 'bob') that are tied to accounts. This leads to a catch-22 because you can't add users without logging in and you can't login because of this error.
> 
> I updated the config file in the release zip:
> https://pastebin.com/raw/vNiDXyCL

Makes sense! 😄 I'll give it a try in the following days as soon as I have some time. 

Thank you for your support and fast answers!
I'll come back with feedback on the final touches :)

**Comment by nymanjens** [comment]
This is done: There is a working image on Docker Hub (nymanjens/facto:v3.26) and I added a working `docker-compose.yml` (in 40dad0d5af51639aba9d178cc02d7662ef60258c).

I'll update the README hereafter
