### ISSUE TITLE
Docker image fails

### ISSUE THREAD

**Issue by enboig** [nymanjens/facto#12]
Just updated and it fails:
```
facto-facto-web-1  | Uncaught error from thread [application-akka.actor.default-dispatcher-10]: hyd
ro/controllers/routes has been compiled by a more recent version of the Java Runtime (class f
ile version 55.0), this version of the Java Runtime only recognizes class file versions up to
 52.0, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]web-1  | Uncaught error from thread [application-akka.actor.default-dispatcher-10]: hyd
ro/controllers/routes has been compiled by a more recent version of the Java Runtime (class f
ile version 55.0), this version of the Java Runtime only recognizes class file versions up to
 52.0, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
```

**Comment by nymanjens** [comment]
If I run the script in the README on my laptop, it works fine

```
# Get the docker-compose.yml file
wget https://raw.githubusercontent.com/nymanjens/facto/master/docker-compose.yml

# Choose a unique random string here of sufficient length
export APPLICATION_SECRET="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"

# Create an empty database with a single admin user
docker-compose run web sleep 5 # Wait for the database to be ready
docker-compose run web bin/server -DdropAndCreateNewDb
docker-compose run web bin/server -DcreateAdminUser

# Bring up the server
docker-compose up
```

A recent change however did change the required java version. Your docker container should now be running java 11. The error message you're getting is likely because you're running the previously required java version (I believe it was v8).

Can you share the commands to reproduce your issue?

**Comment by enboig** [comment]
It fails in my computer. Ubuntu server 22.04 (which shouldn't be important using docker...).

The problem is Java version, maybe it should be upgraded in Dockerfile?

```
dockerroot@servidor7:/mnt/md0/docker/test# docker compose up                    
[+] Running 2/2                                                                                                     
 ✔ Container test-db-1   Running                                                                               0.0s 
 ✔ Container test-web-1  Created                                                                               7.1s 
Attaching to test-db-1, test-web-1                                                                                  
test-web-1  | [info] p.a.d.DefaultDBApi - Database [default] initialized              
test-web-1  | [info] p.a.d.HikariCPConnectionPool - Creating Pool for datasource 'default'                          
test-web-1  | [info] play.api.Play - Application started (Prod) (no global state)                                   test-web-1  | [info] p.c.s.AkkaHttpServer - Listening for HTTP on /0.0.0.0:9000                                     test-web-1  | Uncaught error from thread [application-akka.actor.default-dispatcher-8]: hydro/controllers/routes has
 been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runt
ime only recognizes class file versions up to 52.0, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enable
d for ActorSystem[application]
test-web-1  | java.lang.UnsupportedClassVersionError: hydro/controllers/routes has been compiled by a more recent ve
rsion of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file ver
sions up to 52.0
test-web-1  |   at java.lang.ClassLoader.defineClass1(Native Method)
test-web-1  |   at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
test-web-1  |   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)


```

**Comment by enboig** [comment]
In a new folder I downlaoded de docker-compose.yml
I have run the commands changing only "docker-compose" for "docker compose"
I have run "docker compose pull" and no image was downloaded.
web image is set to "image: nymanjens/facto:latest" in docker-compose, so it should be up to date

**Comment by nymanjens** [comment]
I think I found the problem. Can you try again? `nymanjens/facto:latest` should now resolve to `nymanjens/facto:v3.73`

**Comment by enboig** [comment]
Now it works. Thanks for your time ;-)
