### ISSUE TITLE
"Unable to write to server"

### ISSUE THREAD

**Issue by mtthidoteu** [nymanjens/facto#3]
Hello there!
I have just installed this as docker , however there seems to be a problem with the app writing to the database.
The app just immediately says " Sending data to server failed" when I try and do anything and the log spits out the following:

`[error] a.a.ActorSystemImpl - Internal server error, sending 500 response
java.lang.RuntimeException: WebSocket returned for non WebSocket request
at scala.sys.package$.error(package.scala:27)
at play.core.server.AkkaHttpServer.executeHandler(AkkaHttpServer.scala:317)
at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:244)
at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:137)
at akka.stream.impl.fusing.MapAsync$$anon$25.onPush(Ops.scala:1194)
at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:482)
at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scal`

The database doesn't say anything and not a lot is done.
Cheers

**Comment by nymanjens** [comment]
When I run the Docker setup locally, it works. I have no idea what could cause your problem, sorry.
