### ISSUE TITLE
Could not find ../Hydro

### ISSUE THREAD

**Issue by psi-iota** [nymanjens/facto#7]
In a plain debian VM this time. 
```
Error in custom provider, java.lang.IllegalArgumentException: requirement failed: Could not find ../hydro/facto/conf/accounting-config.yml as file or as resource
  at app.models.accounting.config.ConfigModule.config(ConfigModule.scala:23) (via modules: com.google.inject.util.Modules$OverrideModule -> Module -> app.models.accounting.config.ConfigModule)
  while locating app.models.accounting.config.Config
    for the 1st parameter of app.common.CommonModule.provideClock(CommonModule.scala:21)
  while locating hydro.common.time.Clock
    for the 1st parameter of app.models.access.JvmEntityAccess.<init>(JvmEntityAccess.scala:17)
  at app.models.ModelsModule.configure(ModelsModule.scala:12) (via modules: com.google.inject.util.Modules$OverrideModule -> Module -> app.models.ModelsModule)
  while locating app.models.access.JvmEntityAccess
    for the 3rd parameter of hydro.controllers.Auth.<init>(Auth.scala:16)
  while locating hydro.controllers.Auth
    for the 7th parameter of router.Routes.<init>(Routes.scala:49)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router
    for the 1st parameter of play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:217)
  while locating play.api.http.JavaCompatibleHttpRequestHandler
  while locating play.api.http.HttpRequestHandler
    for the 6th parameter of play.api.DefaultApplication.<init>(Application.scala:236)
  at play.api.DefaultApplication.class(Application.scala:235)
  while locating play.api.DefaultApplication
  while locating play.api.Application
    for the 1st parameter of play.DefaultApplication.<init>(DefaultApplication.java:32)
  at play.DefaultApplication.class(DefaultApplication.java:32)
  while locating play.DefaultApplication
```

**Comment by nymanjens** [comment]
Hi!

You can fix this issue by updating `conf/application.conf` as follows:

```
- app.accounting.configYamlFilePath = "../hydro/facto/conf/accounting-config.yml"
+ app.accounting.configYamlFilePath = "conf/accounting-config.yml"
```

Note however that if you want to run the server, I recommend using the released binary instead. I use the Github code for local development.
